name: Update Submodule in Parent Repo

on:
  push:
    branches:
      - main

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Git config
        run: |
          git config --global user.name "21120079"
          git config --global user.email "hungtruonghl11@gmail.com"

          
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Clone parent repo
        run: git clone --recursive https://github.com/ChisTrun/SkillSharp
      - name: Update submodule in parent repo
        run: |
          cd  SkillSharp
          git checkout -b pikachu_update
          git submodule update --remote frontend/Pikachu
          git add frontend/Pikachu
          git commit -m "Update module to latest commit"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ChisTrun/SkillSharp.git pikachu_update

      - name: Create Pull Request
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"title":"Update module","head":"pikachu_update","base":"main"}' \
          https://api.github.com/repos/ChisTrun/SkillSharp/pulls